---
input_file: ./README.md
output_directory: ./slides
reveal:
  template:
  template_color: FFFFFF
  intro:
  intro_title: Building A REST API Using Swagger
  intro_author: Ashley Roach / DevNet / @aroach
  intro_color: 049FD9
  closing:
  closing_message: Thank you!
  closing_color: 049FD9
